project_id = "ojlfokseswccrzvgkwio"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-downgrade]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.billing-check]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.noxpay-create-pix]
verify_jwt = false

[functions.noxpay-check-status]
verify_jwt = false

[functions.noxpay-webhook]
verify_jwt = false
