project_id = "ojlfokseswccrzvgkwio"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.cancel-downgrade]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
